name: Playwright Cucumber Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Cucumber tags (example: @Login)'
        required: false
        default: ''

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber Tests
        run: |
          if [ -z "${{ github.event.inputs.tags }}" ]; then
            npm run test:with-report1
          else
            npm run test:with-report1 -- --tags="${{ github.event.inputs.tags }}"
          fi
        continue-on-error: true

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
